### ISSUE TITLE
make syntax strict

### ISSUE THREAD

**Issue by lospringliu** [MOACChain/chain3#2]
when run **node --use_strict app.js**,  it shows, I think a **var ** or **const ** should solve
```
> node --use_strict app.js

process controller: api.js...
/Users/xcliu/junk/chain3_restify/node_modules/chain3/lib/chain3/httpprovider.js:34
  XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest; // jshint ignore: line
                 ^
ReferenceError: XMLHttpRequest is not defined
```

**Comment by mdranger** [comment]
What's your question?

**Comment by lospringliu** [comment]
variables should be declared before use

**Comment by lospringliu** [comment]
the problem using PR:  it will be lost when new version is out
library owner should have this in mind

**Comment by mdranger** [comment]
Your comments is received and we have merged it into GIT. Next release version will include it.
Thanks.
