### ISSUE TITLE
同样的代码web3.js不报错，chain3.js报错，可能是版本的原因

### ISSUE THREAD

**Issue by anuxs** [MOACChain/chain3#22]
1、需求：批量生成1万个账户（把公钥、私钥、password写入数据库，把keystore文件保存到目录。

2、以太坊版本： "web3": "^1.2.5-rc.0",
如下代码：
`var acc0 = web3.eth.accounts.create(); 
 console.log(acc0.address,acc0.privateKey);

var w = web3.eth.accounts.wallet.add(acc0);
 console.log(w);
var wls = web3.eth.accounts.wallet.create(1);
console.log(wls);
var kst = wls[0].encrypt(password);
console.log(JSON.stringify(kst));`

两个生成账户的方法都可以运行，不报错，能生成账户，也能保存keystore文件。以太坊在线也能查到账户，证明这个方法没有问题。

3、但是同样的方法，在墨客链遇到问题
`var wls = chain3.mc.accounts.wallet.create(1);
console.log(wls);
var kst = wls[0].encrypt(password);
console.log(JSON.stringify(kst));`
报错：
`TypeError: Cannot read property 'create' of undefined`

4、问题的原因：
其实这个问题在web3.js小于1.0.0的版本也是同样的报错，搜索到stackoverflow.com一篇文章说在0.2以下的版本，这个accounts和wallet都是集合对象，没有create方法，老文档和新文档里面都说有create这个方法，但是老版本其实没实现，新版本实现了，果然更新到1.2.5版本的web3.js之后，create能用了。
chain3.js的最新文档标明了api是1.0.x的，但是npm install chain3 得到的只有    "chain3": "^0.1.22",：

> This documentation is under construction and the chain3.js 1.0 stable version isn’t released. 
文档里面也说了稳定版的1.0还没有发布，那么安装不了1.0.0的chain3.js，那么这两个create不能用的问题还是没有解决的。

5、创建账号为什么不用personal.newAccounts()呢？
前面说了半天需求，是要创建账号（账户、钱包），那为什么不用personal.newAccounts呢？有两个原因，其中最大的原因是我需要得到账户的私钥，后面做交易必须要私钥sign交易信息，没有privatekey啥也干不成。但是personal.newAccounts得到的只有公钥（账户地址）和keystore文件，私钥是用密码加密过的存在keysore文件里面，要得到私钥，必须要用《从keystore得到privateKey》一文提到的keythereum库里面的解密函数，但是卡壳在哪里呢？这个库依赖的几个C语言开发的加密库在mac下面和win下面全部编译失败，无论怎么折腾，keythereum库就是安装不成功，不能由公钥得到私钥了，后面的所有事情都干不了。
那么web3.eth.accounts.create()函数好在哪里呢，它直接返回公钥（账户地址）和私钥，直接返回的私钥！！！，那么我就可以用了。至于生成keystore文件那都是小菜了。
那么chain3.mc.accounts.wallet.create(N)好在哪里呢？这个钱包函数可以批量创建N个账户，全部返回公钥（账号地址）和私钥 ，我直接可以保存到数据库了。一万个账号也就是一句话的功夫。

6、如何解决这个问题：
尽快参照web3.js发布1.0.0的chain3.js，尽快，那么上面的问题都能解决了。
`var wls = chain3.mc.accounts.wallet.create(1);
                                    ^

TypeError: Cannot read property 'create' of undefined
    at Object.<anonymous> (D:\ccbsoft\blockchain_jjrz\vnode\testcode.js:15:37)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:815:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m`

**Comment by mdranger** [comment]
目前chain3 1.0.0的版本还在测试阶段，需要补充应用链的相应接口，NPM发布的是稳定的0.1.22版本
需要使用chain3 1.0.0的可以在1.x的分支下下载
https://github.com/MOACChain/chain3/archive/1.x.zip
