### ISSUE TITLE
chain3.min.js not found after bower install chain3

### ISSUE THREAD

**Issue by wanpixiaozi** [MOACChain/chain3#5]
After run `bower install chain3`, i can't find chain3.min.js at the install directory, so i can't reference chain3 in my HTML file.

**Comment by wanpixiaozi** [comment]
> You need to run gulp to create the chain3.min.js.

gulp can produce chain3.min.js. but 

> bower install chain3
still can't got chain3.min.js
You mean i run gulp in chain3 source directory and copy it to my dst? i don't know how to

**Comment by mdranger** [comment]
You can clone the chain3. Get into Chain, run
npm install
Then run 
gulp
You should find these files:
-rw-r--r--  1 zpli  staff  1257038 Sep 29 23:24 chain3-light.js
-rw-r--r--  1 zpli  staff   542498 Sep 29 23:24 chain3-light.min.js
-rw-r--r--  1 zpli  staff  1352112 Sep 29 23:24 chain3.js
-rw-r--r--  1 zpli  staff  1632154 Sep 29 23:24 chain3.js.map
-rw-r--r--  1 zpli  staff   559565 Sep 29 23:24 chain3.min.js

**Comment by wanpixiaozi** [comment]
I got it
