### ISSUE TITLE
padToEven is not defined

### ISSUE THREAD

**Issue by wanpixiaozi** [MOACChain/chain3#6]
After dl the source, i found 2 issues:
1 padToEven func() come from https://github.com/MOACChain/chain3/blob/master/lib/utils/account.js, but i can't find it's source
2 mocha test failed

**Comment by mdranger** [comment]
Thanks for the info. A new commit is added to the master branch. The padToeven was added. Fo the 2 failed tests, they are for the scs.getTransactionReceipt method. This method is not finalized and should not be put in. We removed it for now and will put back when it's ready.

**Comment by wanpixiaozi** [comment]
Great appreciate your achievements. You may use Travis CI、Coveralls to finish code inspection. https://github.com/ethereumjs/ethereumjs-tx is a good example.
