### ISSUE TITLE
Some cases test failed

### ISSUE THREAD

**Issue by GinMu** [MOACChain/chain3#9]
<img width="985" alt="screen shot 2019-02-26 at 18 12 50" src="https://user-images.githubusercontent.com/12183493/53405237-60c67b00-39f2-11e9-8a38-036e65cda342.png">

**Comment by mdranger** [comment]
please use 'mocha' or 'mocha test'

**Comment by GinMu** [comment]
had committed a [PR](https://github.com/MOACChain/chain3/pull/11) to fix it, pls review.

**Comment by mdranger** [comment]
Review and merged
